stages:
  - pre_check
  - build
  - deploy
  - deploy_docs
  - post_deploy

workflow:
  rules:
    # Disable those non-protected push triggered pipelines
    - if: '$CI_COMMIT_REF_NAME != "master" && $CI_COMMIT_BRANCH !~ /^release\/v/ && $CI_COMMIT_TAG !~ /^v\d+\.\d+(\.\d+)?($|-)/ && $CI_PIPELINE_SOURCE == "push"'
      when: never
    # when running merged result pipelines, it would create a temp commit id. use $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA instead of $CI_COMMIT_SHA.
    # Please use PIPELINE_COMMIT_SHA at all places that require a commit sha
    - if: $CI_OPEN_MERGE_REQUESTS != null
      variables:
        PIPELINE_COMMIT_SHA: $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
        IS_MR_PIPELINE: 1
    - if: $CI_OPEN_MERGE_REQUESTS == null
      variables:
        PIPELINE_COMMIT_SHA: $CI_COMMIT_SHA
        IS_MR_PIPELINE: 0
    - when: always

# global variables
variables:
  GIT_STRATEGY: clone
  AT_FIRMWARE_FROM: gitlab

default:
  retry:
    max: 2
    when: always

include:
  - '.gitlab/ci/rules.yml'
  - '.gitlab/ci/pre_check.yml'
  - '.gitlab/ci/build_template.yml'
  - '.gitlab/ci/build_docs.yml'
  - '.gitlab/ci/build_esp32.yml'
  - '.gitlab/ci/build_esp32c2.yml'
  - '.gitlab/ci/build_esp32c3.yml'
  - '.gitlab/ci/build_esp32c5.yml'
  - '.gitlab/ci/build_esp32c6.yml'
  - '.gitlab/ci/build_esp32c61.yml'
  - '.gitlab/ci/build_esp32s2.yml'
  - '.gitlab/ci/deploy.yml'
  - '.gitlab/ci/post_deploy.yml'
